### ISSUE TITLE
Dependency deduplication breaks `--direct`

### ISSUE THREAD

**Issue by ehoogeveen-medweb** [RSeidelsohn/license-checker-rseidelsohn#23]
`npm` (and I guess alternatives like `yarn` as well) deduplicates dependencies by default, pulling them into the top level of `node_modules`. The `--direct` option doesn't seem to account for this and will list the licenses for all the deduplicated dependencies as well.

As a workaround I can delete the existing `package-lock.json` (and `node_modules`) and run `npm install --legacy-bundling` which effectively disables deduplication, but it would be great if `license-checker-rseidelsohn --direct` ignored deduplicated dependencies (perhaps by only listing licenses for modules included in the `dependencies` and `devDependencies` section of `package.json`).

**Comment by RSeidelsohn** [comment]
Sorry for this taking THAT long, but now I find the time to have a look at this issue. I will keep you updated.

**Comment by RSeidelsohn** [comment]
Hi folks, hello @ehoogeveen-medweb and @avivek,

oh wow, if I understood this correctly, then this bug has been there since `npm > 2`?! Wow.
I have to tell that

1. I don't  have a lot of time for taking care of this project - things might get better once the kids have grown older
2. I took over this whole project from the original (and obviously orphaned) `license-checker`, since when I started using it, we needed an additional option.

So I still do not fully understand all of the code and tests, although over time I of course get better at it. And I love seeing that other people use this fork as well, and some even contribute to it. This really feels great and I feel a bit ashamed that it always thakes that long until I can react to the bug reports and feature requests..

Nevertheless I think I have finally fixed this but with [version 3.0.1](https://github.com/RSeidelsohn/license-checker-rseidelsohn/releases/tag/v3.0.1).
Please go and check it and give some feedback - I rella hope that I fixed this issue for now and ever.

Cheers, Roman.

**Comment by ehoogeveen-medweb** [comment]
It seems to work well, thank you!
